brendel-group/mission_db

backend/cli.py
The interactive mode uses a file to store the history across sessions, but when the user has no permissions for this file the whole interactive mode wouldn't work.\
I added handling of those PermissionErrors and now the interactive mode will work without those permissions, but the history can't be stored for the next time the script is executed.
There are 2 types of Permission Errors:
1. Writing/Creating the history file requires write permission on the directory of the file (users home directory)
2. Reading the history requires read permission
At least under Linux this is the case, but under Windows it should also work.
I also changed the display of default values when removing a tag that is used and it asks for verification:
[Y/n]  would suggest yes is the default but it is no so [y/N] …
=> Add permission denied handling for cli history file

frontend/package-lock.json
There were some vulnerabilitys in the packages (I noticed it by running `npm install`)
This can be addressed by running `npm audit fix`
After updating, the vulnerabilitys are gone (I can see that by running `npm install` again)
=> update frontend packages

frontend/app/utilities/fetchapi.test.ts, frontend/app/utilities/fetchapi.ts, frontend/jest.config.cjs, frontend/jest.setup.cjs, frontend/package-lock.json, frontend/package.json, frontend/tsconfig.jest.json, frontend/tsconfig.json
Resolves #61 
#
- Added config and setup file (`jest.config.cjs` and `jest.setup.cjs`)
- Added some jest devDependencies to `package.json` and `package-lock.json`
- Added  type "jest" to compilerOptions in `tsconfig.json`
- Added module "commonjs" to compilerOptions in new file `tsconfig.jest.json` extending `tsconfig.json`
- Added a test to new file `fetchapi.test.ts` for every function in `fetchapi.ts`
- cd to the frontend directory
- run `npm install`
- run `npm test`
- I had to merge main into my branch to update it
- Therefor Github thinks I did large changes in `package-lock.json`
=> Frontend tests

backend/restapi/tests.py
Hey there, 
this PR adds test cases for the REST API. As the test cases for working with tags have already been included, I've added the general GET and POST Requests, as well as all requests that are working with mission ids.
The test cases are located in [`backend\restapi\tests.py`](https://github.com/brendel-group/mission_db/blob/ec81992a5b54431415d40e98004e99657efc84b8/backend/restapi/tests.py) and running them works by using `python manage.py test restapi`
Hope I covered everything, feel free to point out any cases I forgot :)
This would resolve #60
=> added test cases for restapi

.github/workflows/django.yml, backend/restapi/models.py, backend/tests_cli.py
I noticed that since 
```python
unique_together = ["name", "date", "location", "other"]
```
was added to prevent duplicates, the fields `location` and `other` became required.\
Since it is intended, that these fields are optional and we want to prevent duplicates I changed it to
```python
unique_together = ["name", "date"]
```
since these are the only required fields.\
So now there can't be 2 Missions with the same name and date.
And because #102 was merged we now need to use DATABASE_URL instead of DATABASE_NAME, DATABASE_USER, ... in our `.env` file and also in github actions, so I changed that in github actions.
=> Fix Mission table required fields and DATABASE_URL

frontend/app/pages/details/DatasetTable.tsx, frontend/app/pages/details/DetailsView.tsx, frontend/app/pages/details/StatsView.tsx, frontend/app/pages/missions/Overview.tsx, frontend/app/utilities/fetchapi.ts
Hi,
this pr addresses issue #139
I implemented a new handling for null cases in remarks and location, the problem was the following:
And null appears in detail view:
This is addressed by new checks and changes to the headline in detail view:
=> New handling of null cases in the detail view and in overview

frontend/app/data.tsx, frontend/app/pages/details/InformationView.tsx, frontend/app/pages/missions/Overview.tsx, frontend/app/routes/details.tsx
Hi, this PR introduces the date field into the mission table:
And in the detail view:
Also made clear by additional comments, what is part of the actual mission backend data, and what is obtained by other structures:
```
//This is a local representation used for mission table and details view
export interface RenderedMission {
id: number;
// Pure mission fields
name: string;
location: string;
date: string;
notes: string;
// Inherited from other data structures (details, tags, ...)
totalDuration: string;
totalSize: string;
robot: string;
tags: Tag[];
}
```
Should we rearrange the rows in the mission table?
This PR addresses issue #137
=> Introduced date field to detail view and overview table

.gitignore, backend/backend/settings.py, backend/cli.py, backend/requirements.txt, backend/restapi/tests.py, backend/tests_cli.py, docs/cli/README.md, docs/frontend/README.md, docs/restapi/README.md, frontend/app/utilities/fetchapi.ts, frontend/jest.config.cjs, frontend/package-lock.json, frontend/package.json
This PR adds authorization for the REST API.\
I used [this](https://florimondmanca.github.io/djangorestframework-api-key/) module for this.\
Now every request to the REST API has to have an Authorization header in the format
```
Authorization: Api-Key <API_KEY>
```
This can be disabled by setting `DEBUG=True` in the `backend/backend/.env` file.\
Unfortunately the browsable API won't work with this.
API KEYs can be added or removed via the CLI.
The key itself is not stored in the database, just the hash value.
I made changes and added the documentation for the [CLI](https://github.com/brendel-group/mission_db/blob/feature/restapi-api-key/docs/cli/README.md), the [frontend](https://github.com/brendel-group/mission_db/blob/feature/restapi-api-key/docs/frontend/README.md) and the …
=> Restapi Api Key Authorization

frontend/app/layout/AppShell.tsx
Hi,
I often observe myself clicking the poly bot icon as a home icon. This is now implemented: Clicking the icon redirects the browser to the mission table.
=> Polybot icon now clickable

backend/cli.py, backend/tests_cli.py, docs/cli/README.md
I made some improvements for the interactive mode and the CLI in general:
1. When the output is a table it uses Unicode characters for the lines in the table. This behavior is now optional and can be disabled with the environment variable `USE_UNICODE` that can be set to `False` in the .env file. It then uses ASCII characters.
2. The table now correctly displays strings that contain newlines (`\n`). It now prints the second or more lines of such a string in a new line that contains only empty fields or the respective content.
3. The interactive mode now supports multi line input when using quotes. Previously it was only possible to have multi line strings when using arguments and not the interactive mode.
4. When an exception is thrown when using the interactive mode it is printed like …
=> CLI interactive mode improvements

frontend/app/config.tsx, frontend/app/pages/missions/Overview.tsx, frontend/app/utilities/TagList.tsx, frontend/app/utilities/TagPicker.tsx
resolves #128 
- I replaced the Menu Components in the TagPicker with Popover because this makes it easier to keep the sub menus open. Now Sub menus stay open when clicking on them
- I replaced the color Picker that only had 8 colors with a custom color Input field where you can put any color in hex code
It also gets checked if the hex input is a correct color. If not. There is an error message.
=> Tag picker custom color Input

backend/cli.py, backend/tests_cli.py, docs/cli/README.md
When the CLI prints a table it can happen that the table is too wide for the terminal window and the formatting is messed up and basically unusable.\
To fix this I used to pipe the output of the cli to `less` where I could use the option `-S` and the table gets displayed correctly and I can scroll up, down, left and right with the arrow keys and search for words. Like this:
```bash
./cli.py mission list | less -S
```
With the interactive mode this won't work.\
So I made it that when a table is too wide it automatically gets displayed by a pager that is selected by the `PAGER` or `MANPAGER` environment variable or a default pager.\
For Linux the default pager in most cases is `less`.\
When your pager is `less` you can type in `-S` after it opened to disable long line folding to correctly …
=> Make the CLI use a pager

frontend/app/pages/missions/Overview.tsx, frontend/app/utilities/TagList.tsx, frontend/app/utilities/TagPicker.tsx, frontend/app/utilities/fetchapi.test.ts, frontend/app/utilities/fetchapi.ts
resolves #162 
This PR implements a little menu in the tag picker to change the name and color of an existing tag. This menu replaces the little color palette icon that was used to change the color before.
The new edit tag menu can be opened by clicking on a tag that gets listed in the tag picker
You can change the name and the color there. Once something was changed, the 'Save' button can be clicked.
After clicking the 'Save' button, the changes get saved and the menu closes. Alternatively you can also do that by pressing enter on your keyboard.
There are 3 error cases that get checked once enter or 'Save' was pressed:
- tag name already exists
- tag name is too long
- invaild color
I also disabled the 'Add existing tags' and the 'Remove all tags' buttons if there are no already existing …
=> Tag picker edit tag menu

backend/cli_commands/SyncFolderCommand.py, docs/cli/README.md
A small change that makes the syncfolder command also delete missions that do not exist in the filesystem anymore.
This does not resolve Issue #108 yet because files do not get stored in the database yet. So they can not be synchronised.
In development I was wondering why it is possible to use the arguments "location" and "notes" with the syncfolder command since I don't see a use for these arguments in the syncfolder command. So I removed them
=> syncfolder (delete non existing missions)

frontend/app/pages/missions/Overview.tsx
This fixed the no data found bug in the mission table.
It was caused due to a invalid handling of the loading state. The separate async function for tag loading was removed for this purpose. See issue #176
=> Fixed bug not found bug in mission table.

backend/cli_commands/AddFolderCommand.py, backend/cli_commands/MissionCommand.py
This PR adds functionality to the addfolder command allowing it to add details to the DB.
The mission remove command was also updated so that no file entries remain after their mission is deleted.
The tests for addfolder dont work anymore it now needs an actual file path for it to work. 
New tests still need to be written.
=> addfolder now also adds details

frontend/app/pages/details/DetailsView.tsx
There was a bug in the frontend that happened when the robot name is not included in a file in the backend and became `null` in the frontend.
This resulted in the following error messages when opening the detail view:
In production:
In development:
This fixes that bug.
=> Fix bug when robot name is null

backend/backend/settings.py, frontend/app/utilities/fetchapi.ts
Because of SessionAuthentication it is required to include the csrftoken in the X-CSRFToken header field in the fetch requests to the backend.\
This was not discovered because django doesn't enforce this on GET requests but all others.\
This caused that tags couldn't be created or added to a mission.
I replaced the `header` constant with a function `getHeader`() which retrieves the csrftoken from `document.cookie` and sets the `X-CSRFToken` header.
Adding and creating tags should work again.
=> Include csrf token in X-CSRFToken header

backend/cli_commands/SyncCommand.py
when missions get deleted by the sync command, now also the tags that do not belong to any mission anymore get deleted.
Without this the tags would stay in the database even if they are not belonging to any mission anymore
resolves #171
=> delete unused tag with sync

frontend/app/pages/missions/Overview.tsx
Previously the data in the frontend was shown in random order at the beginning. I think it is more intuitive if it always starts by being sorted by name and then the user can change that sorting if he wants.
But previously if the user selects an order it is not possible to sort the data in the order it began with.
So this minor change just sorts the data by name at the beginning
=> sort data at beginning

frontend/app/pages/details/DetailsView.tsx
As described in issue #190 this bug is addressed with additional checks.
=> Addressed headline bug in detail view

frontend/app/pages/details/InformationView.tsx
Hi,
this PR resolves issue #193. When changing location, the database is updated, but the internal state on the web browser isn't, meaning, continuing to change notes leads to a nonexistent mission (unknown location tag, i. e. location before the change), and vice versa.
=> Fixed bug when changing location and notes field simultaneously

backend/restapi/models.py, backend/restapi/serializer.py, backend/restapi/tests.py, backend/restapi/urls.py, backend/restapi/views.py, docs/restapi/README.md
Hi, this resolves PR #166.
It adds a way to fetch Topics by a file path, which is unique to the system. Topics are only allowed to have specific names, for this purpose, GET, POST and DELETE requests for managing the allowed topic names are added as well.
All new additions are fully tested and documented.
=> Implemented Rest API for topics

frontend/app/pages/error/ErrorPage.module.css, frontend/app/pages/error/ErrorPage.tsx, frontend/app/root.tsx, frontend/app/routes/dataset.tsx, frontend/app/routes/details.tsx
This PR resolves issue #90 by introducing an error screen handled with the [Remix Error Boundary](https://remix.run/docs/en/main/route/error-boundary#errorboundary). 
The new page appears on all page not found errors:
And on invalid urls on the dataset and detail page.
=> Added frontend error handling

frontend/app/fetchapi/details.tsx, frontend/app/fetchapi/tests/details.test.tsx, frontend/app/pages/details/DetailsView.tsx, frontend/app/pages/missions/Overview.tsx, frontend/app/utilities/FormatTransformer.tsx
Hi,
this PR resolves issue #198 by adding a new function to fetch the robot names in the mission table, and also to display them.
An older PR introduced a new way to display the robot names, this function was extended and moved to utilities. 
To test, do the following:
```
import os
import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.settings")
django.setup()
from restapi.models import Mission, File, Mission_files
def add_files_to_mission(mission_id):
try:
mission = Mission.objects.get(id=mission_id)
except Mission.DoesNotExist:
return f"Mission with ID {mission_id} does not exist."
files_data = [
{"file": "geschichte1", "video": "test1.mp4", "robot": "Sheev", "duration": 120, "size": 1024},
{"file": "geschichte2", "video": "test2.mp4", "robot": "Palpatine", "duration": …
```
=> Added robot names to mission table

backend/cli_commands/AddFolderCommand.py, backend/cli_commands/DeleteFolderCommand.py, backend/cli_commands/SyncCommand.py, backend/cli_commands/test_delete_folder.py, backend/restapi/serializer.py, docs/cli/README.md
resolves #109 
When running the `sync` command, the metadata (i.e. location, notes, tags) of each mission gets saved as a json file inside the mission folder
currently there is no check if the metadata changed and needs to be saved. This is something for another issue
=> save metadata on sync command

frontend/app/fetchapi/details.tsx, frontend/app/pages/details/DetailsView.tsx, frontend/app/pages/missions/Overview.tsx, frontend/app/routes/details.tsx, frontend/app/utilities/FormatHandler.tsx
Hi,
this PR resolves the first task of issue #209 by adding a method to truncate names in the detail view.
The main idea behind this is to truncate the common file path, the common file name at the end is not truncated.
For example:
```
/home/simon/Desktop/Teamproject/polybot_mission_db/backend/media/2025.11.11_hiho/train_recording1.mcap
/home/simon/Desktop/Teamproject/polybot_mission_db/backend/media/2025.11.11_hiho/train_recording2.mcap
```
The common path is `/home/simon/Desktop/Teamproject/polybot_mission_db/backend/media/2025.11.11_hiho/` and the files are renamed to `train_recording1.mcap` and `train_recording2.mcap`
This removes visual redundancy while keeping relevant information intact. 
I decided not to modify `getFormattedDetails` because `commonPath` is required for the …
=> Added name truncation

frontend/app/pages/details/InformationView.tsx, frontend/app/pages/missions/Overview.tsx
resolves #191 
- The error in the edit menu now appears when the max length of 65536 is reached so it is consistent with the max length in the database
- notes and location now get showed correctly in the detail view (meaning that line breaks get displayed)
- notes and location get truncated in the overview when they are longer than 42 characters
=> fix the displaying of notes

backend/cli_commands/SyncCommand.py, backend/cli_commands/test_sync_folder.py, backend/requirements.txt, docs/cli/README.md
resolves #108 
- The sync_files function adds Files and their details to the database if they are not in the database yet and it removes Files and their details from the database if they are not in the filesystem anymore
- I added a custom logging handler that tracks if any log message was emitted during the sync_folder command. If no log was emitted, that means that nothing was changed/synced. Therefore the sync command now has a message that tells the user that nothing was synced.
During refactoring I noticed that we use the yaml file to extract data. In the future we want all extraction to happen from the mcap file. But that is something for another Issue
=> Sync files

backend/restapi/serializer.py, frontend/app/data.tsx, frontend/app/fetchapi/details.tsx, frontend/app/fetchapi/tests/details.test.tsx, frontend/app/pages/dataset/DatasetView.tsx, frontend/app/pages/details/DatasetTable.tsx, frontend/app/routes/dataset.tsx
The video is now included in the Dataset View and can be watched there.
I had to change the Dataset View to not take everything as URL parameter but to actually fetch data from the backend to access more data.
I also included two simple links to either download the mcap file or open it in foxglove.
resolves #211 
The design of the Dataset View is currently not beautiful but that will be changed in another task.
Extract a mp4 video of an mcap file with the `mcap_to_mp4.py` script (or any mp4 file) and put it in the backend/media/ folder (maybe in same subfolder as mcap file).\
Add the video to a mcap file with this:
```python
import os
import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "backend.settings")
django.setup()
from restapi.models import File
file = …
```
=> Frontend embed mp4 video

frontend/app/pages/missions/Overview.tsx
When the mission name is long and the page is not wide enough it cuts into the location field like so:
I made it so the text stays in its column
=> bugfix when mission name is long

frontend/app/utilities/TagPicker.tsx
I noticed some things in the tag picker that don't work anymore for some reason and fixed it.
- When changing the name of a tag and the new name is already belonging to a tag that is belonging to another mission, there is an invalid request to the backend to change the name to a name that already exists.
I replaced "tags" with "allTags" to fix this. 
- Also I reset the error messages for the edit tag menu when opening it up because the error message didn't reset when closing the menu. But now it resets the error message correctly
=> fix rename tag bug and error message bug

docs/fetchapi/README.md, frontend/app/data.tsx, frontend/app/fetchapi/tests/topics.test.tsx, frontend/app/fetchapi/topics.tsx
Resolves Issue #167 
#
This PR adds functionality to fetch topics
- ### getTopicsByFile:  
Parameter: path to the file
Return: List of topics in the file | Error message
- ### getAllowedTopics: 
Parameter: None 
Return: List of all allowed topics | Error message
- ### createAllowedTopic: 
Parameter: name of the topic 
Return: The created topic | Error message
- ### deleteAllowedTopic: 
Parameter: name of the topic 
Return: Success response | Error message
- [frontend/app/fetchapi/tests/topics.test.tsx](frontend/app/fetchapi/tests/topics.test.tsx)
- [docs/fetchapi](docs/fetchapi)
- `cd` into frontend directory
- `npm install`
- `npm test`
=> FetchAPI - Topics

frontend/app/data.tsx, frontend/app/fetchapi/details.tsx
resolves #232 
I added a simple check that sets the `videoUrl `in the frontend to `null` if `null` is returned from the backend.\
For that I also had to make `videoUrl` nullable.
The Dataset View for a mcap file without a video should work again.
=> Fix frontend video_url null

frontend/app/pages/details/DetailsView.tsx, frontend/app/pages/details/InformationView.tsx
This resolves issue #241 and issue #242.
As visible on the right, the base path can be easily copied. In addition, the headline does not contain "with" anymore, which fixed  the bug described in issue #242.
=> Added option to copy base path, and fixed a bug in the headline

frontend/app/pages/details/DatasetTable.tsx
Hi, this PR solves issue #245 by adding a new column to visualize the dataset type (train or test). The type is identified by the prefix train/ and test/ from the file path. If the prefix is unknown, the type is replaced by ?.
The prefix train/ and test/ is now omitted in the file name, to prevent visual redundancy. 
To filter for a type, click on a type tag, as previously implemented in the Mission table.
=> Added type tags and filter option to the detail view.

backend/cli_commands/test_command.py, backend/restapi/serializer.py, backend/restapi/tests.py, docs/fetchapi/README.md, frontend/app/data.tsx, frontend/app/fetchapi/details.tsx, frontend/app/fetchapi/tests/details.test.tsx, frontend/app/fetchapi/tests/missions.test.tsx, frontend/app/pages/missions/Overview.tsx, frontend/app/routes/details.tsx
resolves #236 
I removed the functions `getTotalDuration` , `getTotalSize`  and `getRobotNames` from the frontend.
I modified the MissionSerializer, so now the totalDuration, totalSize and the robot names of a Mission get calculated in the Backend by the MissionSerializer.
=> aggregate totalSize/Duration and robots in the backend 

frontend/app/pages/login/LoginPage.module.css, frontend/app/pages/login/LoginPage.tsx
This PR resolves issue #238 
#
- Now when pressing the login button, the text changes from "Log in" to "Logging in . . ." and the dots are animated to show that the page has not hung up or similar.
- The text on the button changes back to "Log in" if the login was not successfull ( `invalid` or `alert`  ).
- The `alert` will be regenerated on submit to prevent the animation from stopping unintentionally
- Now when hovering over the login button, it blurs a bit to show feedback.
=> Add feedback when pressing login button

backend/restapi/serializer.py
When info about a file is requested in the restapi the file_path is obtained with `file.path` but when S3 storage is used it raises an NotImplementedError with the message : 
```
This backend doesn't support absolute paths.
```
I changed the `file.path` to `file.name` and `video.path` to `video.name`.
Now the returned path is not the absolute path to a file but only the path inside the `backend/media/` folder or inside the S3 bucket.
resolves #231 
When using an S3 bucket it should now be possible again to fetch details about a file.
=> Fix S3 does not support absolute paths

docs/fetchapi/README.md, frontend/app/data.tsx, frontend/app/fetchapi/details.tsx, frontend/app/fetchapi/tests/details.test.tsx, frontend/app/pages/details/DatasetTable.tsx, frontend/app/routes/details.tsx
Hi, this PR resolves issue #251 by dynamically recognizing the parent folder of a file.
For example:
successful_picks/bag_1737641283.2575762/bag_1737641283.2575762_0.mcap
successful_picks would be the type. If no type is present, the fallback type is `?`.
The type is always recognized by checking if the mcap file does not start with the same string as the top level folder.
Currently, the database does not provide colors for the type, so i developed a deterministic method to always choose the same colors, it works like this:
Given is a color map, a color index and a dictionary mapping type name to color:
The first encountered type becomes the first color in the list, the next the second, and so on. In case of an overflow, it begins in the front.
In the image you see the current color list, …
=> Added dynamic type handling in the detail view

backend/cli_commands/RestoreDatabaseCommand.py, backend/cli_commands/test_restore_database.py
In the tests for the restore_database command there is a test folder created in the directory.
Currently it is not beeing deleted after the test so the test_mission folder stays in the storage.
I used InMemoryStorage instead of DefaultStorage
=> delete folder after test (bugfix)

.github/workflows/django.yml, README.md, backend/cli_commands/AddFolderCommand.py, backend/cli_commands/GenerateVideoCommand.py, backend/cli_commands/test_add_folder.py, backend/requirements.txt
The videos where generated with the `mp4v` codec which can't be played in some browsers (for example firefox).\
I changed it to `h264/avc1` codec which is supported.
To use this it is necessary to install the python package `opencv-python` not from the binary but to compile it. I adjusted the requirements.txt so that `pip` does that but it may be necessary to install some libraries in you OS. I used this [guide](https://rockyshikoku.medium.com/use-h264-codec-with-cv2-videowriter-e00145ded181) and the `Required build dependencies` section in the [official documentation](https://docs.opencv.org/4.x/d2/de6/tutorial_py_setup_in_ubuntu.html) for installation in Ubuntu.
The compilation by pip takes quite some time (github took ~27min)
I suspect in Ubuntu it is only necessary to install the …
=> Fix video codec

frontend/app/pages/dataset/TopicTable.tsx, frontend/app/pages/details/DatasetTable.tsx
When there is only one mcap file in a mission and you click on it the route falsely gets set as
`http://localhost:5173/dataset?fileName=bag_1728916594.8984177/bag_1728916594.8984177_0.mcap`
instead of the correct route
`http://localhost:5173/dataset?fileName=2024.10.14_picking_apples/test/bag_1728916594.8984177/bag_1728916594.8984177_0.mcap`
This results in a 404 Error
I fixed it and also used this PR to directly sort the Dataset Table by name to make the first time loading of this table more consistent
=> Routing bug

frontend/app/pages/dataset/TopicTable.tsx
Hi,
this PR adds linebreaks in the topic table to prevent situations like this:
Result:
=> Added line breaks in the topic table

backend/cli_commands/GenerateVideoCommand.py, backend/cli_commands/SyncCommand.py
In a previous PR the feature that all videos have their frequency as fps was accidentally removed. 
I added it again.
I also fixed a bug where topics are not added to the database when the metadata.yaml file is missing.
For this fix I just had to initialize the
```python
video_paths: list[str] = []
```
before the try block
=> include frequency as fps again

frontend/app/pages/details/DatasetTable.tsx
The robot menu was missing a placeholder
now there is one
=> add placeholder for robot name menu
